# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenGLVideoPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ffmpeg-kit-ios-full-gpl', '~> 5.1'
#  full-gpl
  # Pods for OpenGLVideoPlayer

end
